@extends('layouts.theme.master')

@section('content')
<main id="main">
<section class="cookie-policy" id="cookie-policy">
      <div class="container">
        <div class="section-title">
          <h1>Intuitive Website Cookies Policy Statement</h1>
        </div>
        <div class="cookie-policy-content">
          <p>We, Intuitive Technology Partners Inc. <b>(“Intuitive” “We” “Us” “Our”)</b> are the owners of the website <a href="www.intuitive.cloud">www.intuitive.cloud</a> <b>(“Website”).</b> We are committed to protecting the privacy and security of your personal information. We may use cookies or similar technologies to analyze information about your use of our website.</p>

          <p>We use cookies that are necessary to run our website and improve your experience while navigating through the website. We also use cookies to provide you with relevant information in your searches on our and other websites. The additional cookies are only used with your consent.</p>

          <p>We advise you to carefully read this Cookies Policy Statement <b>(“Policy”),</b> together with the Company’s <b>Privacy Statement</b> <a href="privacy-statement.html">https://www.intuitive.cloud/privacy-statement/</a> so that you are aware of the cookies and technologies used as well as how we treat your personal information.</p>

          <p><b>PLEASE READ THIS COOKIES POLICY STATEMENT CAREFULLY. BY CLICKING “I AGREE” OR BY CONTINUING TO USE THE WEBSITE, PROVIDING US PERSONAL INFORMATION, YOU CONSENT TO OUR USE OF YOUR PERSONAL INFORMATION IN ACCORDANCE WITH THE TERMS OF THIS COOKIES POLICY STATEMENT. IF YOU DO NOT AGREE TO THIS COOKIES POLICY STATEMENT, YOU MAY WITHDRAW YOUR CONSENT.</b></p>

          <p><b>IF YOU ARE ACCESSING THE WEBSITE ON BEHALF OF A THIRD PARTY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO ACCEPT THIS COOKIES POLICY STATEMENT ON BEHALF OF SUCH THIRDPARTY. IN SUCH AN EVENT, YOUR USE OF THE WEBSITE SHALL REFER TO USE BY SUCH THIRD PARTY. IF YOU DO NOT HAVE SUCH AN AUTHORITY OR DO NOT AGREE TO THE TERMS OF THIS COOKIES POLICY STATEMENT, THEN YOU SHOULD REFRAIN FROM USING THE WEBSITE.</b></p>

          <ol>
            <li>
              <p><b>What are Cookies?</b></p>
              <p>Cookies are alphanumeric files which are placed on to your device when you visit a website. It allows us to recognize your device and store some information about your preferences or past actions, analyze trends, to learn about our user base, operate and improve our services and provide you with a better experience when you visit our website.</p>
              <ul>
                <li>
                   <b>Permanent Cookie:</b> Permanent cookies help us recognize you as an existing user, so it is easier for you to return to the website without signing in again. After signing in, the permanent cookies stay on your browser and will be read when you return on to our website. These remain on your computer/device for a predefined period.
                </li>
                <li>
                  <b>Session Cookies:</b> Session cookies only last for as long as the session exists. They get erased when the user closes the browser.
                </li>
              </ul>
            </li>
            <li class="mt-3">
              <p><b>Types of Cookies Used</b></p>
              <p>Mentioned below are some of the types of cookies used by us but may not be limiting to the ones mentioned below:</p>
              <ul>
                <li>
                  <b>Permanent Cookie:</b> Permanent cookies help us recognize you as an existing user, so it is easier for you to return to the website without signing in again. After signing in, the permanent cookies stay on your browser and will be read when you return on to our website. These remain on your computer/device for a predefined period.
                </li>
                <li>
                  <b>Session Cookies:</b> Session cookies only last for as long as the session exists. They get erased when the user closes the browser.
                </li>
                <ul>
                  <p>As for the domain to which it belongs, there are either:</p>
                  <li>
                    <b>First-Party Cookies:</b> These cookies are set by the web server of the visited page and share the same domain.
                  </li>
                  <li><b>Third-Party Cookies:</b> These cookies are placed by third party on your device and may provide information to us and third parties about your usage of the website.</li>
                  <li><b>Analytical Tools:</b> We may use Google Analytics or any other similar analytics tool as a web analytics service. The analytical tools may use cookies, text files that are stored on your computer and enable analysis of your use of our website. The information generated by the cookies about your use of our website are usually transferred to a server and stored there. We do not control third 
                  party cookies. You can also prevent the data generated by the cookies from being stored or transferred. Please refer this below further to understand the same.</li>
                </ul>
              </ul>
            </li>
            <li class="mt-3">
              <p><b>Use of Cookies</b></p>
              <p>We use personal information captured through cookies to make your interaction with us faster and more secure. They may be used for the following purposes but not limiting to:</p>
              <ul>
                <li>
                  <b>Preferences:</b> Cookies allows the website to remember information that changes the way the website behaves or looks, such as your preferred language or the region you are in. Remembering your preferences enables us to personalize and display advertisements and other contents for you.
                </li>
                <li>
                  <b>Security/Optimization:</b> Cookies allow us to maintain security by authenticating users, preventing fraudulent use of login credentials and protect user data from unauthorized parties. We may use certain type of cookies to allow us to block many types of attacks, such as attempts to steal content from the forms present on the website.
                </li>
                <li>
                  <b>Processing:</b> Cookies enable the website to work efficiently. Basis such cookies, we are able to deliver services that a website visitor expects, like navigating around web pages or accessing secure areas of the website.
                </li>
                <li>
                  <b>Advertising:</b> We use cookies to make advertising more engaging to our users. Some common applications of cookies are made to select advertising based on what is relevant to you, to improve reporting on campaign performance and to avoid showing ads you would have already seen. Cookies capture information about how you interact with the website, which includes the pages that you visit most.
                </li>
                <li>
                  <b>Communication:</b> We may use information collected via cookies to communicate with you, for sending newsletters, seeking your opinion and feedback, and providing you services and promotional materials.
                </li>
                <li>
                  <b>Analytics and Research:</b> We may use cookies to better understand how people use our products/services so that we can improve them.
                </li>
              </ul>
            </li>
            <li class="mt-3">
              <p><b>Manage Cookies</b></p>
              <p>You can decide whether to accept or manage the cookies. You can manage the cookies by adjusting the settings on your browser. Disabling cookies may affect the functionality of our website.</p>
              <p>You can set your browser:</p>
              <ul>
                <li>To allow all cookies</li>
                <li>To allow only 'trusted' sites to send them</li>
                <li>To manage the cookies from websites as per the requirement</li>
              </ul>
              <p>We recommend not to block all cookies because www.intuitive.cloud website uses them to work properly.</p>
              <p>Please read the below steps to find out <b>How to Manage Cookies in Major Browsers:</b></p>
              <p><b>Google Chrome:</b><br>Click on the “Menu” tab in the upper-right corner and then click on “Settings”</p>
              <p>To block cookies:<br>Settings → Click on “Advanced” to expand → Under Privacy and Security, Click on “Content Settings” → Click on “Cookies” → To block cookies, Click on toggle button next to this line “Allow sites to save and read cookie data (recommended)“ → This will block the cookies.</p>
              <p>To check cookies:<br>Settings → Click on “Advanced” to expand → Under Privacy and Security → Click on “Content Settings” → Click on “Cookies” → See all cookies and site data → Click on the website and check the cookies used in that site.</p>
              <p><b>Mozilla Firefox:</b>Click on the Menu tab in the upper-right corner → Click on Options → In the left side navigation, Click on Privacy and Security → Under History, Select “Use Custom setting for history” from the Drop down → Click on Show Cookies Buttons → Select the file which you want to remove and then click on remove selected button.</p>
              <p><b>Safari:</b> Open Safari → Click on Preferences from Safari menu → Go to Privacy tab → Click on “Remove all Website data” to remove all the stored data → Click Remove now button from the pop-up → Click on Details button under “Remove all Website data” → Select the sites you want to remove the data → Click Remove → Click Done.</p>
              <p><b>Microsoft Edge:</b> Open Microsoft Edge → Click on settings menu in the upper-right corner → Click on Cookie &amp; Site Permissions → Cookies and site data → Click on enable OR Disable sites to save and read cookie data. More options are available in subsequent tabs.</p>
            </li>
            <li>
              <p><b>Changes to This Statement</b></p>
              <p>We may periodically update this Cookie Policy to reflect changes in our practices. Please revisit this page periodically to stay aware of any changes to this Cookies Policy Statement. If we modify this Policy, we will make it available through the website and indicate the date of the latest revision. If needed, in such situations we may even prompt you to revisit your cookie settings and submit your preferences again</p>
            </li>
            <li>
              <p><b>Contact Us </b></p>
              <p>If you have any questions or concerns regarding this Policy, you can contact us at <a href="mailto:arc@intuitive.cloud">arc@intuitive.cloud.</a></p>
            </li>
          </ol>


        </div>
      </div>
    </section>

</main>
    <!-- /main -->
@endsection
@section('js')
<script>
	// $(document).ready(function(){
	// 	// getData();
	// })
	// function categopost(ids){
	// 	var data = new FormData();
	// 	data.append('id', ids);
	// 	var response = runAjax('{{route("ajax.category.post.list")}}', data); 
	// 	if(response.status == '200'){
	// 		$('#data-list').empty();
	// 		if(response.data.length > 0){
	// 			var htmlData = '';
	// 			$.each(response.data, function( index, value ) {
	// 				//var date = moment.unix(value.timestamp).format("DD-MMMM-YYYY (h:mm a)");
	// 				htmlData+= '<div class="col-lg-6 col-md-6 mb-4"><div class="blog-details"><div class="blog-image"><img src="'+ value.image+'" class="img-fluid" /></div>'+
	// 								'<div class="blog-content"><h4>'+ value.title+'</h4><div class="blogdesc"><p class="mb-4">'+ value.description+'</p></div>'+
	// 								'<a href="/blog/'+ value.id+'">Read More</a></div></div></div>';
								
	// 				})
	// 			$('#data-list').html(htmlData);
	// 		}
	// 	}
	// }
	// GET LIST
	// function getData(){
	// 	var data = new FormData();
	// 	data.append('page', $('#filterBox #page').val());
	// 	data.append('count', $('#filterBox #count').val());
	// 	data.append('status', $('input[name="statusRadio"]:checked').val());
	// 	var response = adminAjax('{{route("ajax.category.list")}}', data); 
	// 	if(response.status == '200'){
	// 		$('#data-list').empty();
	// 		if(response.data.length > 0){
	// 			var htmlData = '';
	// 			$.each(response.data, function( index, value ) {
	// 				//var date = moment.unix(value.timestamp).format("DD-MMMM-YYYY (h:mm a)");
	// 				htmlData+= '<tr>'+
	// 								'<th scope="row">'+ value.id +'</th>'+
	// 								'<td><img src="'+ value.image +'" height="50px" width="50px"></td>'+
	// 								'<td>'+ value.title +'</td>'+
	// 								'<td>'+ value.priority +'</td>'+
	// 								'<td>'+ value.status +'</td>'+
	// 								'<td>'+ value.action +'</td>'+
	// 							'</tr>';
	// 			})
	// 			$('#data-list').html(htmlData);
	// 		}
	// 	}
	// }
</script>
@endsection
